dictionaries:
  - case_common_doc_court
  - case_common_doc_result
  - case_common_document_type
  - case_common_judge
  - case_common_type
  - case_court_type
  - case_doc_district_rf
  - case_doc_instance
  - case_doc_subject_rf_code
  - case_document_result

arrays:
  - case_common_event_m2
  - u_common_case_defendant_m
  - case_common_parts_m2_search
