name:       transform
version:    0.1.0.0
license:    MIT
author:     "Max Taldykin"
copyright:  "2023"

ghc-options:
  - -Wall
  - -Werror
  - -O2
  - -funbox-strict-fields

default-extensions:
  - DeriveGeneric
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedStrings
  - TupleSections
  - NamedFieldPuns
  - RecordWildCards

executables:
  transform:
    main: Main.hs
    source-dirs: .
    dependencies:
      - aeson
      - base
      - bytestring
      - lens
      - lens-aeson
      - pandoc
      - text
      - mtl
      - containers
      - yaml
      - unliftio
      - vector
